apply a broader attempt at #1983

diff --git a/.github/workflows/qc.yml b/.github/workflows/qc.yml
--- a/.github/workflows/qc.yml
+++ b/.github/workflows/qc.yml
@@ -33,34 +33,34 @@ jobs:
       run: pip3 install pyyaml typing graphstore/rule-runner
     ## Users.
     - name: Test users schema.
-      run: kwalify -E -m metadata/users.schema.yaml
+      run: kwalify -E -m metadata/users.schema.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     - name: Test users metadata.
-      run: kwalify -E -f metadata/users.schema.yaml metadata/users.yaml
+      run: kwalify -E -f metadata/users.schema.yaml metadata/users.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     ## Groups.
     - name: Test groups schema.
-      run: kwalify -E -m metadata/groups.schema.yaml
+      run: kwalify -E -m metadata/groups.schema.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     - name: Test groups metadata.
-      run: kwalify -E -f metadata/groups.schema.yaml metadata/groups.yaml
+      run: kwalify -E -f metadata/groups.schema.yaml metadata/groups.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     ## DB Xrefs.
     - name: Test dbxrefs schema.
-      run: kwalify -E -m metadata/db-xrefs.schema.yaml
+      run: kwalify -E -m metadata/db-xrefs.schema.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     - name: Test dbxrefs metadata.
-      run: kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml  2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
+      run: kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     ## Datasets.
     - name: Test datasets schema.
-      run: kwalify -E -m metadata/datasets.schema.yaml
+      run: kwalify -E -m metadata/datasets.schema.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     - name: Test datasets metadata.
-      run: kwalify -E -f metadata/datasets.schema.yaml metadata/datasets/*.yaml
+      run: kwalify -E -f metadata/datasets.schema.yaml metadata/datasets/*.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     ## Extension constraints.
     - name: Test extension constraints schema.
-      run: kwalify -E -m metadata/extensions-constraints.schema.yaml
+      run: kwalify -E -m metadata/extensions-constraints.schema.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     - name: Test extension constraints metadata.
-      run: kwalify -E -f metadata/extensions-constraints.schema.yaml metadata/extensions-constraints.yaml
+      run: kwalify -E -f metadata/extensions-constraints.schema.yaml metadata/extensions-constraints.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     ## GO reference species set.
     - name: Test reference species set schema.
-      run: kwalify -E -m metadata/go-reference-species.schema.yaml
+      run: kwalify -E -m metadata/go-reference-species.schema.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     - name: Test reference species set metadata.
-      run: kwalify -E -f metadata/go-reference-species.schema.yaml metadata/go-reference-species.yaml
+      run: kwalify -E -f metadata/go-reference-species.schema.yaml metadata/go-reference-species.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
     ## Cross-test metadata
     - name: Cross-test users and groups.
       run: python3 ./scripts/sanity-check-users-and-groups.py --verbose --users metadata/users.yaml --groups metadata/groups.yaml
