file checks locally with buffer #1983

diff --git a/.github/workflows/qc.yml b/.github/workflows/qc.yml
--- a/.github/workflows/qc.yml
+++ b/.github/workflows/qc.yml
@@ -34,7 +34,7 @@ jobs:
     ## Users.
     - name: Test users schema.
       run: |
-        kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | grep 'INVALID\|ERROR' > invalid.log
+        kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | grep 'INVALID\|ERROR' > invalid.log || true
         test $(stat -c %s invalid.log) -eq 0
     - name: Test users metadata.
       run: kwalify -E -f metadata/users.schema.yaml metadata/users.yaml 2>&1 | grep 'INVALID\|ERROR' && false || true
